# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['social_monitor_gui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('scripts/common.py', 'scripts'),
        ('scripts/competitor_monitor.py', 'scripts'),
        ('scripts/url_detail.py', 'scripts'),
        ('scripts/hot_search.py', 'scripts'),
        ('scripts/keyword_search.py', 'scripts'),
        ('scripts/weibo_hot_search.py', 'scripts'),
        ('scripts/xiaohongshu_scraper.py', 'scripts'),
        ('scripts/weibo_scraper.py', 'scripts'),
        ('scripts/douyin_hot_search.py', 'scripts'),
        ('notify', 'notify'),
        ('.env', '.'),
    ],
    hiddenimports=['pydantic', 'requests'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 重型包，我们的代码不需要
        'PyQt5', 'PySide', 'PyQt6', 'PySide6',
        'tensorflow', 'tensorboard', 'keras',
        'torch', 'torchvision', 'torchaudio',
        'numpy', 'pandas', 'matplotlib', 'PIL', 'cv2',
        'scipy', 'scikit_learn', 'sklearn',
        'openai', 'tiktoken',
        'flask', 'fastapi', 'uvicorn', 'django',
        'jupyter', 'ipython', 'notebook', 'jedi', 'parso',
        'prompt_toolkit', 'zmq', 'jupyter_client',
        'lxml', 'bs4',
        'selenium',
        'streamlit', 'gradio',
        'setuptools',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='社交监控工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
